version: "3.1"

services:
  db:
    image: supabase/postgres
    restart: always
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.postgres:/var/lib/postgresql/data
